namespace Callsign.UI.Services;

public sealed record RuntimeStateSnapshot(
    string ServiceState,
    string? RuntimeRole,
    string StatusMessage,
    string? ActiveCallsign,
    string? VerifiedCallsign,
    string? PendingCommand,
    string? PendingApp,
    string? LastLaunchedApp,
    bool IsListening,
    string ModeDescription,
    DateTime UpdatedUtc,
    string SessionState,
    string? LastTranscriptText = null,
    double? LastTranscriptConfidence = null,
    DateTime? LastTranscriptUpdatedUtc = null,
    IReadOnlyList<string>? RecentTranscriptHistory = null,
    string? OverlayReadout = null,
    string? CurrentWakeWordEngine = null,
    string? LastWakeWordEngine = null,
    double? LastWakeWordScore = null,
    double? WakeWordThreshold = null,
    IReadOnlyList<string>? WakeWordAudioQualityWarnings = null,
    bool? IsSpeechActive = null,
    DateTime? LastSpeechActivityUtc = null,
    string? LastMicrophoneLevelState = null,
    double? LastMicrophoneRawRms = null,
    double? LastMicrophonePeak = null,
    double? LastMicrophoneGainDb = null,
    double? LastMicrophoneNoiseFloorRms = null,
    double? LastMicrophoneSpeechThresholdRms = null,
    double? LastMicrophoneClippingRatio = null,
    IReadOnlyList<string>? LastMicrophoneWarnings = null,
    bool ServiceDictationActive = false,
    string? ServiceDictationText = null,
    DateTime? ServiceDictationUpdatedUtc = null,
    IReadOnlyList<string>? ServiceDictationHistory = null,
    string? RequestedUiMode = null,
    DateTime? RequestedUiModeUtc = null,
    string? LastIdentityTranscript = null,
    bool? LastIdentityAccepted = null,
    string? LastIdentityMatchedVariant = null,
    double? LastIdentityConfidence = null,
    string? LastIdentityRejectReason = null,
    string? LastIdentityRetryPrompt = null,
    bool? LastIdentityBiometricAccepted = null,
    double? LastIdentityBiometricScore = null,
    double? LastIdentityBiometricThreshold = null,
    double? LastIdentityBiometricDistance = null,
    double? LastIdentityBiometricNearMatchThreshold = null,
    string? LastIdentityBiometricEngine = null,
    string? LastIdentityBiometricRejectReason = null,
    string? LastIdentityEnrollmentEmbeddingPath = null,
    int? CurrentProcessId = null,
    DateTime? ProcessStartedUtc = null,
    string? ActiveMicrophoneDeviceName = null,
    DateTime? LastAudioPacketUtc = null,
    bool? CanHearAudio = null,
    double? SecondsSinceLastAudioPacket = null,
    string? RuntimeAuthorityStatus = null,
    bool? IsAuthoritativeUserRuntime = null,
    string? LastServiceActionKind = null,
    string? LastServiceActionTarget = null,
    string? LastServiceActionMessage = null,
    bool? LastServiceActionSucceeded = null,
    DateTime? LastServiceActionUtc = null,
    IReadOnlyList<RuntimeServiceActionSnapshot>? RecentServiceActions = null);

public sealed record RuntimeServiceActionSnapshot(
    string Kind,
    string? Target,
    string Message,
    bool Succeeded,
    DateTime Utc);
