<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Callsign.Service</RootNamespace>
    <AssemblyName>Callsign.Service</AssemblyName>
    <ApplicationIcon>..\..\assets\callsign.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Callsign.Extensions\Callsign.Extensions.csproj" />
    <ProjectReference Include="..\Callsign.UI\Callsign.UI.csproj" />
  </ItemGroup>
</Project>
